spring:
  r2dbc:
    url: r2dbc:postgresql://*.*.*.*:5432/postgres
    username: *
    password: *
    pool:
      enabled: true
      initial-size: 50
      max-size: 100

logging:
  level:
    org.springframework.r2dbc: debug
  config: classpath:log4j2-dev.yml