spring:
  r2dbc:
    url: r2dbc:postgresql://*.*.*.*:5432/postgres
    username: *
    password: *
    pool:
      enabled: true
      initial-size: 50
      max-size: 100

  jpa:
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true

logging:
  level:
    org.springframework.r2dbc: debug
  config: classpath:log4j2-dev.yml